# Window geometry
WINDOW_SIZE = '320x450'

# Colors
BACKGROUND_COLOR = '#E6F2E8'
BACKGROUND_COLOR_DARKER = '#CADFBF'
BUTTON_COLOR1 = '#3B8686'
BUTTON_COLOR2 = '#93C5A8'
BUTTON_TEXT_COLOR = 'white'
BUTTON_TEXT_COLOR1 = '#3B8686'
BUTTON_TEXT_COLOR2 = '#93C5A8'
ERROR_COLOR = 'red'
TEXT_COLOR1 = '#2E7272'
TEXT_COLOR2 = '#6CAB9E'
ACTIVE_TEXT_COLOR = 'red'

# Fonts
TITLE_FONT = ('Arial', 18, 'bold')
LABEL_FONT = ('Arial', 12)
LABEL_FONT_BOLD = ('Arial', 12, 'bold')
LABEL_FONT_MINI = ('Arial', 10)
BUTTON_FONT = ('Arial', 12, 'bold')
